### PR TITLE
Add go 1.11 tool

### PR DESCRIPTION
**Pull request by magik6k**
Fixes https://github.com/ipfs/testing/issues/139

### CODE REVIEW

**Comment by Stebalien** [comment]
Does this "just work" or do we need to cut a new gx release (and build it with go 1.11).

**Comment by magik6k** [comment]
We need this first (to be able select go 1.11 in Jenkinsfile - which for go-ipfs happens in https://github.com/ipfs/go-ipfs/blob/master/ci/Jenkinsfile#L38)

**Comment by magik6k** [comment]
(this needs to be merged and you need to ping @VictorBjelkholm to kick jenkins in some way I don't know/have access to)

**Comment by victorb** [comment]
Will confirm here once deployed.

**Comment by victorb** [comment]
@magik6k @Stebalien ok, been deployed now and should be available in pipelines.

**Pull request merged**
