### PR TITLE
Add basic go-ipfs configuration

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Comment by victorb** [comment]
FYI: workspace should be ignored, right now it seems to have been added as a git submodule. Workspaces are safe to throw away since they come from git repositories.

**Comment by Kubuxu** [comment]
Removed

**Comment by victorb** [comment]
Seems all good to me! However, seems to include work from https://github.com/ipfs/jenkins/pull/13 so let's merge that one first and then we can merge this.

**Review by victorb — APPROVED** [review]

**Comment by victorb** [comment]
@Kubuxu after merging #13 I still see commits that are not supposed be here. Could you make sure everything is correct?

**Comment by Kubuxu** [comment]
@VictorBjelkholm fixed

**Comment by victorb** [comment]
Sweet! @lgierth please review and if all good = merge

**Comment by ghost** [comment]
I think this looks good to me

**Review by ghost — APPROVED** [review]

**Pull request merged**
